// Renders objective outcomes after evaluation; this component is never mounted before submit.
import { CheckCircle2, CircleX } from 'lucide-react'

function SimulationResult({ result, onRestart }) {
  return (
    <section className="simulation-result" aria-labelledby="result-title" tabIndex="-1">
      <p className="eyebrow">Objective result</p>
      <h2 id="result-title">{result.correctCount} of {result.totalTasks} tasks correct</h2>
      <p className="result-score">{result.percentage}%</p>
      <p>These outcomes are generated by deterministic mock rules for this Phase 1 interface.</p>
      <ol className="outcome-list">
        {result.outcomes.map((outcome) => (
          <li className="outcome-item" key={outcome.taskId}>
            {outcome.isCorrect
              ? <CheckCircle2 aria-hidden="true" size={22} />
              : <CircleX aria-hidden="true" size={22} />}
            <div>
              <h3>{outcome.title}</h3>
              <p><strong>{outcome.isCorrect ? 'Correct.' : 'Needs review.'}</strong> {outcome.explanation}</p>
            </div>
          </li>
        ))}
      </ol>
      <button className="button button--secondary" type="button" onClick={onRestart}>
        Try again
      </button>
    </section>
  )
}

export default SimulationResult
